Rapport des sites (html)
=========================================================================================

Répartition des sites par statut de protection et par type d'espaces protégés.
----------------------------------------------------------------------------------

Ce rapport au format html permet de présenter les résultats en utilisant la célèbre librairie de statistique R.

```{r, echo=F}
opts_chunk$set(fig.width=12, fig.height=8)
library("ggplot2")
library("reshape2")
library("rgdal")
library("RgoogleMaps")
```

Situation générale du site.
----------------------------------------
Situé en France ce site présente peu d'impact sur les zones à statuts de protection fortes.

```{r, echo=F}
poly<-spTransform(place.place, CRS("+init=epsg:4326"))
lat <- coordinates(poly)[2]
lon <- coordinates(poly)[1]
center = c(lat, lon)
marker <- paste("&markers=color:blue|label:I|", lat, sep="")
marker <- paste(marker, lon, sep=",")
France <- GetMap(center=center, zoom=5, markers = marker, destfile = "../france1.png", maptype="hybrid") 
PlotOnStaticMap(France, center=center, add = F)
text(lat,lon,place.place$rec_name)
```

Situation localisée du site.
-----------------------------------------
```{r, echo=F}
MyMap <- GetMap(center=center, zoom=10, markers = marker, destfile = "../MyTile.png", maptype="hybrid")
protection <- spTransform(protection.area, CRS("+init=epsg:4326"))
protection <- SpatialPolygons(protection@polygons,proj4string=protection@proj4string)
buff<-place.place
tampon500 <- gBuffer(buff, width=500, quadsegs=20)
tampon500<-spTransform(tampon500, CRS("+init=epsg:4326"))
tampon2000 <- gBuffer(buff, width=2000, quadsegs=20)
tampon2000<-spTransform(tampon2000, CRS("+init=epsg:4326"))
tampon5000 <- gBuffer(buff, width=5000, quadsegs=20)
tampon5000<-spTransform(tampon5000, CRS("+init=epsg:4326"))
tampon10000 <- gBuffer(buff, width=10000, quadsegs=20)
tampon10000<-spTransform(tampon10000, CRS("+init=epsg:4326"))
PlotPolysOnStaticMap(MyMap, protection, lwd=.5, col = rgb(1,1,1,0.4), add = F)
PlotPolysOnStaticMap(MyMap, tampon10000, lwd=.5, col = rgb(1,0,0,0.1), add = T)
PlotPolysOnStaticMap(MyMap, tampon5000, lwd=.5, col = rgb(1,0,0,0.1), add = T)
PlotPolysOnStaticMap(MyMap, tampon2000, lwd=.5, col = rgb(1,0,0,0.2), add = T)
PlotPolysOnStaticMap(MyMap, tampon500, lwd=.5, col = rgb(1,0,0,0.3), add = T)

text(lat,lon,place.place$rec_name)
legend("topright", c("Protection","Buffer 500m","Buffer 2000m","Buffer 5000m","Buffer 10000m"), fill = c(rgb(1,1,1,0.4),rgb(1,0,0,0.1),rgb(1,0,0,0.2),rgb(1,0,0,0.3),rgb(1,0,0,0.4) ), title="Légende")
```

Diagramme des surfaces par type d'espaces protégés
--------------------------------------------------

```{r, echo=F}
Data <- data.frame(protection.surface_statut_buffer[c("statut", "surface", "type")])
colnames(Data)<-c("Statut", "Surface", "Type")
ggplot(Data, aes(x=Type, y=Surface, fill=Statut))+
  geom_bar(stat="identity")+
  theme(legend.position=c(0.22,0.8))
```

Graphique radar représentant les sites en proportion de leur surface par type de statuts de protection.
-------------------------------------------------------------------------------------------------------

```{r, echo=F}
Data <- data.frame(protection.surface_statut_buffer[c("statut", "surface", "type")])
colnames(Data)<-c("Statut","Surface", "Type")
tab.m <- melt(Data, id=c("Statut", "Type"))
ggplot(tab.m, aes(x=variable, y=value, fill=Statut)) + 
  geom_bar(stat='identity', position='fill') +  coord_polar(theta = "y") + 
  scale_x_discrete("") + theme(axis.title.y=element_blank()) +  
  theme(legend.position=c(0.9,0.26)) +
  facet_wrap(~Type, ncol=2)
```

Cartographie des sites concernés.
-----------------------
```{r, echo=F}
plot(protection.area['id'], col=rainbow(25,alpha=0.35))
```


